### ISSUE TITLE
Disabling manual control with service set_manual_control is giving errors about brightness_pct

### ISSUE THREAD

**Issue by fwump38** [basnijholt/adaptive-lighting#119]
I'm able to call the service to set manual control to true without issue. Recently (within the past week or so) I started getting errors when trying to call the service to disable manual control.

From the Developer page -> Call Service, this is what I was testing:

```
service: adaptive_lighting.set_manual_control
data:
  entity_id: switch.adaptive_lighting_al
  manual_control: false
  lights: light.lr_lamp
```
  
 Here is the log after enabling debug mode:
 
```
This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/adaptive_lighting/switch.py:733
Integration: Adaptive Lighting
First occurred: 12:18:05 PM (1 occurrences)
Last logged: 12:18:05 PM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'brightness_pct'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 566, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 630, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/adaptive_lighting/switch.py", line 246, in handle_set_manual_control
    await switch._adapt_lights(
  File "/config/custom_components/adaptive_lighting/switch.py", line 846, in _adapt_lights
    await self._adapt_light(light, transition, force=force, context=context)
  File "/config/custom_components/adaptive_lighting/switch.py", line 733, in _adapt_light
    brightness = round(255 * self._settings["brightness_pct"] / 100)
KeyError: 'brightness_pct'
```

I originally thought this was because I was using a group (of lights) for the `lights:` parameter but switching to a single light produced the same results.

**Comment by fwump38** [comment]
I think this is related to #112 as I was also seeing the errors related to sunrise. Strangely, Adaptive Lighting wasn't showing as an installed repo for me in HACS so I added it, installed it and restarted HA and everything appears to be working now (though I've abandoned the automation I had to set manual control for specific rooms in favor of multiple "installs" of Adaptive Lighting for each room and using the `switch.adaptive_lighting_<room_name>` to toggle rooms instead.

**Comment by robtesch** [comment]
This is still an issue for me with the same stack trace, it happens on all of my `adaptive_lighting.apply` service calls from all of my automations.

```
Logger: homeassistant.components.automation.xx_my_automation_xx
Source: custom_components/adaptive_lighting/switch.py:772
Integration: Automation (documentation, issues)
First occurred: 15:23:26 (2 occurrences)
Last logged: 15:23:26

XX My Automation XX: Error executing script. Unexpected error for call_service at pos 2: 'brightness_pct'
While executing automation automation.xx_my_automation_xx
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 368, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 568, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 666, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/adaptive_lighting/switch.py", line 222, in handle_apply
    await switch._adapt_light(  # pylint: disable=protected-access
  File "/config/custom_components/adaptive_lighting/switch.py", line 772, in _adapt_light
    brightness = round(255 * self._settings["brightness_pct"] / 100)
KeyError: 'brightness_pct'
```

**Comment by anoblet** [comment]
Any update on this?
