### ISSUE TITLE
Error calling adaptive_lighting.apply

### ISSUE THREAD

**Issue by anoblet** [basnijholt/adaptive-lighting#190]
#### Version information:
1.0.14
#### Description:
When I try to call `adaptive_lighting.apply`  with the following YAML:

```
entity_id: switch.adaptive_lighting_kitchen
lights: light.kitchen_lights
```

I receive the following error:

```
2021-09-14 13:37:21 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'brightness_pct'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 665, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/config/custom_components/adaptive_lighting/switch.py", line 224, in handle_apply
await switch._adapt_light( # pylint: disable=protected-access
File "/config/custom_components/adaptive_lighting/switch.py", line 780, in _adapt_light
brightness = round(255 * self._settings["brightness_pct"] / 100)
KeyError: 'brightness_pct'
```

**Comment by basnijholt** [comment]
This problem is solved by https://github.com/basnijholt/adaptive-lighting/pull/326.

Please update to 1.0.20! 😄
