### ISSUE TITLE
Build 4de7e8d. After update this one all switches become unavailable

### ISSUE THREAD

**Issue by poudenes** [basnijholt/adaptive-lighting#20]
Hi Bas,

After I updated your latest build 4de7e8d and restart HA. All switches become unavailable.

A reinstall and reboot of HA didn't help

**Comment by poudenes** [comment]
Seems it brick more things. Automation with switch and turn on light actions are also not working anymore

**Comment by tomasz8w** [comment]
Same here. After update this shows up in log:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/adaptive_lighting/switch.py", line 243, in async_setup_entry
    sleep_mode_switch = SimpleSwitch("Sleep Mode", False, hass, config_entry)
  File "/config/custom_components/adaptive_lighting/switch.py", line 861, in __init__
    self._unique_id = f"{self._name}_{slugify(self._which)}"
AttributeError: 'SimpleSwitch' object has no attribute '_name'
```

**Comment by poudenes** [comment]
da0b255: solved the problem!

**Comment by basnijholt** [comment]
Yes, sorry about that!
