### ISSUE TITLE
Flooded service light turn on. 

### ISSUE THREAD

**Issue by meanmrgreen** [basnijholt/adaptive-lighting#211]
Third time this has happened the last month. All of a sudden i notice i can't turn any lights on. HA is very slow and the logs are flooding with errors about not being able to turn on lights service. 

I'm including the logs i found. Looks like it has been going on all day 

- Latest hassOS in proxmox VM. 
- Using ZHA with about 5-6 lightning groups
- conbee 2 stick and Ikea bulbs. 

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:128
First occurred: 21 oktober 2021 06:48:08 (71 occurrences)
Last logged: 09:18:39

Unable to find referenced entities media_player.emby_lucas_tv
Unable to find referenced entities light.kontoret_takbelysning
Unable to find referenced entities media_player.googlehome2104
Unable to find referenced entities light.badrummet
Unable to find referenced entities light.nedre_hall_takbelysning
```

```
Logger: homeassistant.components.recorder
Source: components/recorder/__init__.py:444
Integration: Recorder (documentation, issues)
First occurred: 10:17:37 (1 occurrences)
Last logged: 10:17:37

The recorder queue reached the maximum size of 30000; Events are no longer being recorded
```

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:528
First occurred: 10:32:33 (2 occurrences)
Last logged: 15:45:20

Updating state for light.nedre_badrum_spotlights_zha_group_0x000a (<class 'homeassistant.components.zha.light.LightGroup'>) took 0.699 seconds. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+zha%22
Updating state for light.nedre_badrum_takbelysning (<class 'homeassistant.components.zha.light.Light'>) took 0.629 seconds. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+zha%22
```

```
Logger: homeassistant.core
Source: components/zha/light.py:257
First occurred: 09:52:54 (42358 occurrences)
Last logged: 19:05:29

Error executing service: <ServiceCall light.turn_on (c:adapt_lgt_abbe_interval_2068082): entity_id=['light.nedre_badrum_spotlights_zha_group_0x000a'], params=transition=0.0, brightness=145, color_temp=454>
Error executing service: <ServiceCall light.turn_on (c:adapt_lgt_abbe_interval_2069878): entity_id=['light.nedre_badrum_spotlights_zha_group_0x000a'], params=transition=0.0, brightness=145, color_temp=454>
Error executing service: <ServiceCall light.turn_on (c:adapt_lgt_abbe_interval_2070081): entity_id=['light.nedre_badrum_spotlights_zha_group_0x000a'], params=transition=0.0, brightness=145, color_temp=454>
Error executing service: <ServiceCall light.turn_on (c:adapt_lgt_abbe_interval_2070380): entity_id=['light.nedre_badrum_spotlights_zha_group_0x000a'], params=transition=0.0, brightness=145, color_temp=454>
Error executing service: <ServiceCall light.turn_on (c:adapt_lgt_abbe_interval_2068628): entity_id=['light.nedre_badrum_spotlights_zha_group_0x000a'], params=transition=0.0, brightness=145, color_temp=454>
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1507, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 462, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/zha/light.py", line 582, in async_turn_on
    await super().async_turn_on(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/zha/light.py", line 257, in async_turn_on
    result = await self._color_channel.move_to_color_temp(temperature, duration)
  File "/usr/local/lib/python3.9/site-packages/zigpy/group.py", line 44, in request
    res = await self.application.mrequest(
  File "/usr/local/lib/python3.9/site-packages/zigpy_deconz/zigbee/application.py", line 211, in mrequest
    with self._pending.new(req_id) as req:
  File "/usr/local/lib/python3.9/site-packages/zigpy/util.py", line 262, in new
    raise ControllerException(f"duplicate {sequence} TSN") from AssertionError
zigpy.exceptions.ControllerException: duplicate 175 TSN

```

**Comment by RubenKelevra** [comment]
Hey @meanmrgreen,

did you solve the issue?

**Comment by meanmrgreen** [comment]
Solved it by putting the transition time above 0 (1 sec). Haven't had it since

//Mvh Johan Löfstedt
________________________________

**Comment by RubenKelevra** [comment]
Cool 😎
