### ISSUE TITLE
Error in log after HA reboot

### ISSUE THREAD

**Issue by stefanroelofs** [basnijholt/adaptive-lighting#23]
I see the following error after a HA reboot:
```
2020-10-22 21:23:49 ERROR (MainThread) [homeassistant.components.switch] Error while setting up adaptive_lighting platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 481, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/adaptive_lighting/switch.py", line 890, in async_added_to_hass
    if (last_state is None and self._initial_state) or last_state.state == STATE_ON:
AttributeError: 'NoneType' object has no attribute 'state'
```
i configured 2 light entities:
- light.kitchen_ceiling_group
- light.dining_area_ceiling_group

These are both ZHA zigbee groups. Could it be that they are not yet available during boot?

**Comment by basnijholt** [comment]
Fixed in https://github.com/basnijholt/adaptive-lighting/commit/4ffa6fc0e4ee313764aba824dca9e5fb9c0cf06c.

**Comment by stefanroelofs** [comment]
Thanks!
