### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by jamespreedy** [basnijholt/adaptive-lighting#232]
#### Version information:
1.0.14

#### Description:
I get the below error appearing in my Home Assistant core logs.
Error doing job: Task exception was never retrieved
It doesn't seem to be related to a particular action on my part.

Please let me know if I can get any additional information, or can help at all.
Thanks in advance!

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/adaptive_lighting/switch.py:1445 
Integration: Adaptive Lighting (documentation, issues) 
First occurred: 8:35:39 am (26 occurrences) 
Last logged: 9:23:55 am

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
    if await self.turn_on_off_listener.maybe_cancel_adjusting(
  File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
    id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
`

I've included the full paste from my logs below too.

`2021-12-12 09:23:49 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2021-12-12 09:23:50 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2021-12-12 09:23:50 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2021-12-12 09:23:50 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2021-12-12 09:23:50 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2021-12-12 09:23:50 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2021-12-12 09:23:54 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2021-12-12 09:23:55 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2021-12-12 09:23:55 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2021-12-12 09:23:55 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2021-12-12 09:23:55 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2021-12-12 09:23:55 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2021-12-12 09:23:55 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2021-12-12 09:23:55 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 944, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1445, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'`

**Comment by jamespreedy** [comment]
Additional example.

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/adaptive_lighting/switch.py:1474 
Integration: Adaptive Lighting (documentation, issues) 
First occurred: 10:08:40 am (5 occurrences) 
Last logged: 10:08:41 am

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
    if await self.turn_on_off_listener.maybe_cancel_adjusting(
  File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
    id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'`

**Comment by jamespreedy** [comment]
@RubenKelevra - I saw you added the above label so thought I would provide an update on this issue.

I'm still seeing this issue with v1.0.15.
I've included more log examples below - I hope these help.

`2022-01-10 14:45:09 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2022-01-10 14:45:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2022-01-10 14:45:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2022-01-10 14:45:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2022-01-10 14:45:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2022-01-10 14:45:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
2022-01-10 14:45:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'`

If there are any specific logs I can get for you, or anything that I'm able to test, or verify, please let me know.

**Comment by RubenKelevra** [comment]
@jamespreedy well, I've added this label to all issues, to keep a record of what is related to v1 stuff, while I work on version 2. :)

The error looks pretty harmless, it seems to just miss a "is this variable Null" check somewhere. 

Is this breaking any functionality for you? Else I would just "leave it" and invest my time in v2 which will eventually fix this anyway :)

**Comment by jamespreedy** [comment]
Exciting - thanks in advance for your good work on v2 - this is a great custom component!

So I'm not sure one is a definitely cause of the other, but it feels like the above issue is a part of what's causing my other errors below. Honestly I'm just hoping I've done something silly!

`2022-01-10 20:15:32 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'async_turn_on'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 587, in _async_call_service_step
await self._async_run_long_action(service_task)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 548, in _async_run_long_action
long_task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 273, in service_handler
await script_entity.async_turn_on(
AttributeError: 'NoneType' object has no attribute 'async_turn_on'
2022-01-10 20:15:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140042466079936] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 527, in handle_execute_script
await script_obj.async_run(msg.get("variables"), context=context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1260, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 587, in _async_call_service_step
await self._async_run_long_action(service_task)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 548, in _async_run_long_action
long_task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 273, in service_handler
await script_entity.async_turn_on(
AttributeError: 'NoneType' object has no attribute 'async_turn_on'`


In short, motion triggers my automations which in turn call a script to turn the lights on.
When the lights come on they use the adaptive lighting component to chose the correct brightness and colour temp.

An example of an automation ...

`# ===============================================================
# Snug Spotlights On
# ===============================================================

- id: '9BA29A79-4951-4D95-A23B-D161CB3F5156'
  alias: "Snug Spotlights / Timer Idle / On"
  mode: restart

  trigger:
  - entity_id: binary_sensor.snug_multisensor_1_motion
    platform: state
    to: 'on'
  - entity_id: binary_sensor.snug_multisensor_2_motion
    platform: state
    to: 'on'
  - entity_id: binary_sensor.snug_camera_motion
    platform: state
    to: 'on'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: timer.snug
        state: 'idle'
      - condition: state
        entity_id: input_boolean.snug_override
        state: 'off'
      - condition: state
        entity_id: input_select.hassio_alarm_state
        state: 'Evening'
      - condition: state
        entity_id: media_player.snug_tv
        state: 'off'

  action:
  - service: timer.start
    entity_id: timer.snug

  - service: script.turn_on_snug_lights_evening

  - service: timer.cancel
    entity_id: timer.snug_tv

# ===============================================================`

And an example of the script it calls.


`# ===============================================================
# Snug Lights
# ===============================================================

 turn_on_snug_lights_evening:
   alias: "Turn on the Snug Lights / Evening"
   mode: restart

   sequence:
     - service: light.turn_on
       data_template:
         entity_id:
           - light.snug_spotlights
         brightness_pct: "{{ state_attr('switch.adaptive_lighting_default','brightness_pct') | float(1) }}"
         color_temp: "{{ state_attr('switch.adaptive_lighting_default','color_temp_mired') | int(153) }}"

     - service: light.turn_on
       data_template:
         entity_id:
           - light.snug_play_bars
         brightness_pct: "{{ state_attr('switch.adaptive_lighting_default','brightness_pct') | float(1) }}"
         color_name: purple

# ===============================================================`

**Comment by jamespreedy** [comment]
I'm so sorry about the formatting of the above ... that clearly could have gone better! 🤦🏻‍♂️

**Comment by jamespreedy** [comment]
My lights should have turned on this morning automatically, and didn't, but my logs are littered with 61x errors.
Calling the script to turn the lights on manually generates another error below.


2022-01-14 07:37:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'

2022-01-14 07:37:11 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'

2022-01-14 07:37:11 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'

2022-01-14 07:37:11 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'

2022-01-14 07:37:11 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'

2022-01-14 07:37:11 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'


Thanks for your previous advice @RubenKelevra - it *is* pretty harmless, but it does mean that my lights aren't coming on!

My scripts above aren't super complicated. I'm definitely not saying this is more important than v2 🤣, but could you perhaps think of a different way of me doing this that would mean that my lights would work, and I wouldn't get these errors every time a motion sensor triggers the script?

Thanks in advance! 🍺

**Comment by RubenKelevra** [comment]
> I'm so sorry about the formatting of the above ... that clearly could have gone better! 🤦🏻‍♂️

You can fix this, just put ``` in the line above and below your code :)

**Comment by jamespreedy** [comment]
> 

You sir, are a legend, thanks! Fixed. 😀
Every day is a school day ...

**Comment by Tommatheussen** [comment]
I see this happen from time to time as well. For me it only happens when I have restarted Home Assistant, I have KNX lights set up that get turned on by KNX motion sensors (no HA in between) to 6%. This integration then adjusts them to the appropriate %.
Maybe it's some sort of race condition that tries to increase the brightness before the KNX lights have reported their state back or something, a restart usually fixes it for me

**Comment by basnijholt** [comment]
This issue should be fixed by #325.

Please update to 1.19.0 :)

**Comment by jamespreedy** [comment]
Awesome sauce - thank you very much! 🍺
