### ISSUE TITLE
'SimpleSwitch' object has no attribute '_lights'

### ISSUE THREAD

**Issue by bruvv** [basnijholt/adaptive-lighting#267]
#### Version information:
Version: core-2022.3.3
Installation Type: Home Assistant OS
Version of AL: 1.0.15

#### Description:
I noticed in my logs that there is an error. So far it is not breaking anything and my adaptive lighting is working just fine. So I am not sure why or when it happens.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 192, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 949, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/adaptive_lighting/switch.py", line 227, in handle_apply
    all_lights = switch._lights
AttributeError: 'SimpleSwitch' object has no attribute '_lights'
```

**Comment by ronaldtveen** [comment]
Same exact thing here, takes up about 25% of my complete log 🤔

**Comment by basnijholt** [comment]
You should update both Home Assistant and Adaptive Lighting to fix this.

**Comment by ronaldtveen** [comment]
I'm running Adaptive Lighting `v1.4.1` and Home Assistant:
```
Home Assistant 2023.1.7
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest
```

I'm still getting this error message a lot:

```
2023-01-24 07:51:58.254 ERROR (MainThread) [homeassistant.components.automation.lighting_automagically_on_adaptive] Lighting | Automagically on (adaptive): Error executing script. Unexpected error for call_service at pos 3: 'SimpleSwitch' object has no attribute '_lights'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 787, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/adaptive_lighting/switch.py", line 246, in handle_apply
    all_lights = switch._lights
AttributeError: 'SimpleSwitch' object has no attribute '_lights'
```

Any idea what's causing this to still show up?

**Comment by bruvv** [comment]
I'm not getting the issue so that's why I'm closing it. But I've reopened the issue.

**Comment by th3w1zard1** [comment]
Anyone still getting this issue? Please post your adaptive-lighting config, set debug logging to true (see the readme) and post any other relevant information you think others might need to reproduce this issue.

**Comment by ronaldtveen** [comment]
> Anyone still getting this issue? Please post your adaptive-lighting config, set debug logging to true (see the readme) and post any other relevant information you think others might need to reproduce this issue.

Yes, problem still here for me. I'll try and get the info for you and update this issue soon(ish)!

**Comment by th3w1zard1** [comment]
@ronaldtveen Ensure you're using the latest version of `adaptive-lighting` in HACS, which is 1.4.1.

**Comment by ronaldtveen** [comment]
I'm indeed running the latest v1.4.1 @th3w1zard1

Yesterday (2023-03-25) it errored 192 times. I've only just now added the debug logger to the config so I expect to see more information later tonight when adaptive lighting actually kicks in. What that results into something different I will update this issue of course.

```
2023-03-25 22:05:35.190 ERROR (MainThread) [homeassistant.components.automation.lighting_automagically_on_adaptive] While executing automation automation.lighting_automagically_on_adaptive
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 545, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 795, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/config/custom_components/adaptive_lighting/switch.py", line 246, in handle_apply
    all_lights = switch._lights
AttributeError: 'SimpleSwitch' object has no attribute '_lights'
```

The automation that turns on the (adaptive) lighting is the following;
It runs quite often, that is the only thing I'm thinking might not be as designed?
```
alias: Lighting | Automagically on (adaptive)
description: Turn lights on after sunset when we are home, or just got home
trigger:
  - platform: state
    entity_id: sun.sun
    attribute: elevation
    id: sun_elevation
  - platform: state
    entity_id:
      - zone.home
  - platform: state
    entity_id:
      - input_boolean.bedtime
      - input_boolean.movie_time
      - input_boolean.lighting_manual_mode
  - platform: numeric_state
    entity_id: sensor.downstairs_illuminance_average
    below: "45"
  - platform: state
    entity_id:
      - binary_sensor.landing_motion
      - binary_sensor.hallway_motion
      - binary_sensor.kitchen_motion
      - binary_sensor.hallway_front_door_sensor
condition:
  - condition: numeric_state
    entity_id: zone.home
    above: "0"
    alias: Home is occupied
  - condition: state
    entity_id: input_boolean.bedtime
    state: "off"
  - condition: state
    entity_id: input_boolean.lighting_manual_mode
    state: "off"
  - condition: state
    state: "off"
    entity_id: input_boolean.movie_time
  - condition: numeric_state
    entity_id: sensor.downstairs_illuminance_average
    below: 45
action:
  - service: light.turn_on
    data: {}
    target:
      device_id:
        - 1030e44a698a2e4bc6b98a1ccf305341
        - a63ee52d16651a7fb015dbb971d4d5c5
        - a0ebbd71b62b84f071993984df8901b3
      entity_id:
        - light.living_room_wall
        - light.tv_left
        - light.tv_right
  - if:
      - condition: sun
        after: sunset
      - condition: state
        entity_id: light.garden_christmas_lights
        state: "off"
    then:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.garden_christmas_lights
    alias: Garden lights
    else: []
  - service: adaptive_lighting.apply
    data:
      entity_id: switch.adaptive_lighting_adapt_color_downstairs
  - service: adaptive_lighting.apply
    data:
      entity_id: switch.adaptive_lighting_adapt_color_living_room
mode: parallel
max: 50
```

I have two instances that are created through the GUI so I cannot share the yaml of that. This is what I could find in the `.storage`;
```
{
  "entry_id": "a18460996f776eb3cf03d00aee07848f",
  "version": 1,
  "domain": "adaptive_lighting",
  "title": "Downstairs",
  "data": {
    "name": "Downstairs"
  },
  "options": {
    "lights": [
      "light.bank",
      "light.eethoek",
      "light.hallway_ceiling",
      "light.keuken",
      "light.toilet",
      "light.tv_left",
      "light.tv_right"
    ],
    "prefer_rgb_color": false,
    "initial_transition": 1.0,
    "sleep_transition": 1.0,
    "transition": 45.0,
    "interval": 90,
    "min_brightness": 1,
    "max_brightness": 75,
    "min_color_temp": 2000,
    "max_color_temp": 4000,
    "sleep_brightness": 1,
    "sleep_rgb_or_color_temp": "color_temp",
    "sleep_color_temp": 1000,
    "sleep_rgb_color": [
      255,
      56,
      0
    ],
    "sunrise_time": "None",
    "max_sunrise_time": "None",
    "sunrise_offset": 0,
    "sunset_time": "None",
    "min_sunset_time": "None",
    "sunset_offset": 0,
    "only_once": false,
    "take_over_control": true,
    "detect_non_ha_changes": true,
    "separate_turn_on_commands": false,
    "send_split_delay": 0,
    "adapt_delay": 0
  },
  "pref_disable_new_entities": false,
  "pref_disable_polling": false,
  "source": "user",
  "unique_id": "Downstairs",
  "disabled_by": null
},
```
...and:
```
{
  "entry_id": "01a8ff50ec59bc1ceaf054f4e677d6bd",
  "version": 1,
  "domain": "adaptive_lighting",
  "title": "Upstairs",
  "data": {
    "name": "Upstairs"
  },
  "options": {
    "lights": [
      "light.landing",
      "light.study"
    ],
    "prefer_rgb_color": false,
    "initial_transition": 1.0,
    "sleep_transition": 3.0,
    "transition": 45.0,
    "interval": 90,
    "min_brightness": 1,
    "max_brightness": 100,
    "min_color_temp": 2000,
    "max_color_temp": 5500,
    "sleep_brightness": 1,
    "sleep_rgb_or_color_temp": "color_temp",
    "sleep_color_temp": 1000,
    "sleep_rgb_color": [
      255,
      56,
      0
    ],
    "sunrise_time": "None",
    "sunrise_offset": 0,
    "sunset_time": "None",
    "sunset_offset": 0,
    "only_once": false,
    "take_over_control": true,
    "detect_non_ha_changes": true,
    "separate_turn_on_commands": false,
    "adapt_delay": 0
  },
  "pref_disable_new_entities": false,
  "pref_disable_polling": false,
  "source": "user",
  "unique_id": "Upstairs",
  "disabled_by": null
},
```

**Comment by th3w1zard1** [comment]
@ronaldtveen 
I'm indeed running the latest v1.4.1 @th3w1zard1
Uhhh the latest version is 1.6.0 as of yesterday, maybe try updating?

**Comment by ronaldtveen** [comment]
Uhhh I didn't see that in HACS. 
Just re-downloaded it and now running v1.6.0, will keep you updated.

**Comment by ronaldtveen** [comment]
That version does indeed seems to fix it @th3w1zard1!
Great job. I'll keep a close eye on it for the coming days, but this looks very promising.

👍

**Comment by bruvv** [comment]
Ill close it, thanks for the updates @th3w1zard1 !
