### ISSUE TITLE
Error executing service: ServiceCall light.turn_on

### ISSUE THREAD

**Issue by pankrusheff** [basnijholt/adaptive-lighting#374]
#### Version information:
Adaptive Lighting 1.2.1
HA core-2022.11.2
#### Description:
after adding the configuration to the AL integration and setting (by default, I select only the lamps that I want to use in the current configuration). The following error appears in the logs. It is repeated every time when it is necessary to adapt the configuration to changed conditions.
#### Log

 ```
Logger: homeassistant.core
Source: components/yeelight/light.py:265 
First occurred: 23:42:54 (1 occurrences) 
Last logged: 23:42:54

Error executing service: <ServiceCall light.turn_on (c:adapt_lgt:b'VYor':sleep:b'0R'): entity_id=['light.ceiling_light_livingroom_1'], params=transition=1.0, brightness=4, color_temp=370, color_temp_kelvin=2702>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 245, in _async_wrap
    return await func(self, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 704, in async_set_default
    await self._bulb.async_set_default()
  File "/usr/local/lib/python3.10/site-packages/yeelight/aio.py", line 38, in wrapper
    cmd = await self.async_send_command(
  File "/usr/local/lib/python3.10/site-packages/yeelight/aio.py", line 96, in async_send_command
    raise BulbException(response["error"])
yeelight.main.BulbException: {'code': -5006, 'message': 'illegal request'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1762, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 570, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 802, in async_turn_on
    await self.async_set_default()
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 265, in _async_wrap
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error when calling async_set_default for bulb Yeelight Ceiling19 0x183c7f3b at 192.168.68.157: {'code': -5006, 'message': 'illegal request'}
```

**Comment by basnijholt** [comment]
Does this mean that when you execute this:
```yaml
service: light.turn_on
data:
  entity_id: light.ceiling_light_livingroom_1
  transition: 1.0
  brightness: 4
  color_temp: 370
  color_temp_kelvin: 2702
```
in the `localhost:8123/developer-tools/service` tool, you get the same error?

**Comment by pankrusheff** [comment]
> in the localhost:8123/developer-tools/service tool, you get the same error?

Yes. 
```

Logger: homeassistant.core
Source: components/yeelight/light.py:265 
First occurred: 01:48:29 (6 occurrences) 
Last logged: 09:12:51

Error executing service: <ServiceCall light.turn_on (c:adapt_lgt:b'WFS_':light_event:b'8U'): entity_id=['light.ceiling_light_livingroom_1'], params=transition=1.0, brightness=255, color_temp=277, color_temp_kelvin=3610>
Error executing service: <ServiceCall light.turn_on (c:adapt_lgt:b'WFS_':interval:b'8v'): entity_id=['light.ceiling_light_livingroom_1'], params=transition=45.0, brightness=255, color_temp=275, color_temp_kelvin=3636>
Error executing service: <ServiceCall light.turn_on (c:adapt_lgt:b'WFS_':interval:b'8~'): entity_id=['light.ceiling_light_livingroom_1'], params=transition=45.0, brightness=255, color_temp=273, color_temp_kelvin=3663>
Error executing service: <ServiceCall light.turn_on (c:adapt_lgt:b'WFS_':interval:b'9R'): entity_id=['light.ceiling_light_livingroom_1'], params=transition=45.0, brightness=255, color_temp=271, color_temp_kelvin=3690>
Error executing service: <ServiceCall light.turn_on (c:adapt_lgt:b'WFS_':light_event:b'9s'): entity_id=['light.ceiling_light_livingroom_1'], params=transition=1.0, brightness=255, color_temp=271, color_temp_kelvin=3690>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 245, in _async_wrap
    return await func(self, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 704, in async_set_default
    await self._bulb.async_set_default()
  File "/usr/local/lib/python3.10/site-packages/yeelight/aio.py", line 38, in wrapper
    cmd = await self.async_send_command(
  File "/usr/local/lib/python3.10/site-packages/yeelight/aio.py", line 96, in async_send_command
    raise BulbException(response["error"])
yeelight.main.BulbException: {'code': -5006, 'message': 'illegal request'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1762, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 570, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 802, in async_turn_on
    await self.async_set_default()
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 265, in _async_wrap
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error when calling async_set_default for bulb Yeelight Ceila 0x1a61929d at 192.168.68.158: {'code': -5006, 'message': 'illegal request'}

```

**Comment by kuduacz** [comment]
Hi. i have same error with my yellight color bulb:

Rejestrator: homeassistant.core
Źródło: core.py:2814
Pierwsze zdarzenie: 13:49:09 (1 zdarzenia)
Ostatnio zalogowany: 13:49:09

Error executing service: <ServiceCall light.turn_on (c:01JKQYG2VV:al:IRXW:ntrv:02): entity_id=['light.jola'], params=transition=45.0, brightness=255, rgb_color=(255, 236, 221)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 249, in _async_wrap
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 703, in async_set_default
    await self._bulb.async_set_default()
  File "/usr/local/lib/python3.13/site-packages/yeelight/aio.py", line 48, in wrapper
    cmd = await self.async_send_command(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/yeelight/aio.py", line 116, in async_send_command
    raise BulbException(response["error"])
yeelight.main.BulbException: {'code': -5006, 'message': 'illegal request'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2814, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2837, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_lighting/hass_utils.py", line 62, in service_func_proxy
    await existing_service.job.target(call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 644, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 801, in async_turn_on
    await self.async_set_default()
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 269, in _async_wrap
    raise HomeAssistantError(
    ...<2 lines>...
    ) from ex
homeassistant.exceptions.HomeAssistantError: Error when calling async_set_default for bulb Yeelight Color 0x12a1c6c6 at 192.168.5.7: {'code': -5006, 'message': 'illegal request'}
