### ISSUE TITLE
Failure while getting the configuration

### ISSUE THREAD

**Issue by 3v1n0** [basnijholt/adaptive-lighting#423]
Just opening on configure for any item and I get:

```
2023-01-29 18:36:44.922 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 218, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 229, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 256, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 374, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/adaptive_lighting/config_flow.py", line 94, in async_step_init
    all_lights = [
  File "/config/custom_components/adaptive_lighting/config_flow.py", line 97, in <listcomp>
    if _supported_features(self.hass, light)
  File "/config/custom_components/adaptive_lighting/switch.py", line 421, in _supported_features
    supported_features = state.attributes[ATTR_SUPPORTED_FEATURES]
KeyError: 'supported_features'
``

**Comment by 3v1n0** [comment]
FYI, using ´supported_features = state.attributes.get(ATTR_SUPPORTED_FEATURES, {})´ instead makes it work, but not sure if something is missing somewhere else.

**Comment by th3w1zard1** [comment]
What hass version are you using? That's very strange indeed, you said this happens whenever you try adding a config entry to the integration?

**Comment by th3w1zard1** [comment]
Possibly related to #112
