### ISSUE TITLE
light.turn_on errors in 1.0.0b0 with tasmota 

### ISSUE THREAD

**Issue by jes1417** [basnijholt/adaptive-lighting#50]
I am getting theses errors pretty consistently

```
Logger: homeassistant.core
Source: components/tasmota/light.py:229
First occurred: 9:32:56 PM (53 occurrences)
Last logged: 10:02:15 PM

Error executing service: <ServiceCall light.turn_on (c:adapt_lgt_b7ef_interval_18): entity_id=['light.back_porch'], params=transition=45.0, brightness=196, white_value=196, color_temp=500>

Error executing service: <ServiceCall light.turn_on (c:adapt_lgt_b7ef_interval_19): entity_id=['light.porch'], params=transition=45.0, brightness=196, white_value=196, color_temp=500>

Error executing service: <ServiceCall light.turn_on (c:adapt_lgt_b7ef_interval_19): entity_id=['light.back_porch'], params=transition=45.0, brightness=196, white_value=196, color_temp=500>

Error executing service: <ServiceCall light.turn_on (c:adapt_lgt_18fd_interval_20): entity_id=['light.downstairs_bath'], params=transition=45.0, brightness=74, white_value=74, color_temp=500>

Error executing service: <ServiceCall light.turn_on (c:adapt_lgt_18fd_interval_21): entity_id=['light.downstairs_bath'], params=transition=45.0, brightness=73, white_value=73, color_temp=500>

Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/core.py", line 1461, in catch_exceptions await coro_or_task File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service await handler.job.target(service_call) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service await self.hass.helpers.service.entity_service_call( File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call future.result() # pop exception if have File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call await coro File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call await result File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 230, in async_handle_light_on_service await light.async_turn_on(**params) File "/usr/src/homeassistant/homeassistant/components/tasmota/light.py", line 229, in async_turn_on self._tasmota_entity.set_state(True, attributes) File "/usr/local/lib/python3.8/site-packages/hatasmota/light.py", line 274, in set_state self._set_state_light(state, attributes) File "/usr/local/lib/python3.8/site-packages/hatasmota/light.py", line 343, in _set_state_light speed = round(transition * 2 / delta_ratio) ZeroDivisionError: float division by zero
```

I was not getting these before the upgrade to the new beta.

**Comment by basnijholt** [comment]
This is definitely a bug with `core`, so I recommend creating an issue there!

It happens in
```
_set_state_light speed = round(transition * 2 / delta_ratio) ZeroDivisionError: float division by zero
```
Where `delta_ratio` becomes 0, which shouldn't be allowed.

**Comment by jes1417** [comment]
Thank you
