### ISSUE TITLE
HACS failing to install AL: <Integration basnijholt/adaptive-lighting> [config_flow.py] was not downloaded

### ISSUE THREAD

**Issue by basslet** [basnijholt/adaptive-lighting#599]
# Home Assistant Adaptive Lighting Issue Template

## Bug Reports

If you need help with using or configuring Adaptive Lighting, please [open a Q&A discussion thread here](https://github.com/basnijholt/adaptive-lighting/discussions/new?category=q-a) instead.

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

Confirm.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

```
2023-05-22 12:38:38.523 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/translations/cs.json, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 4
2023-05-22 12:38:38.544 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/const.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 4
2023-05-22 12:38:38.550 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/__init__.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 4
2023-05-22 12:38:38.556 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/config_flow.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 4
2023-05-22 12:38:38.561 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/_docs_helpers.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 4
2023-05-22 12:38:38.567 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/translations/da.json, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 4
2023-05-22 12:39:40.522 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/config_flow.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 3
2023-05-22 12:39:40.531 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/__init__.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 3
2023-05-22 12:39:40.537 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/const.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 3
2023-05-22 12:39:40.543 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/translations/cs.json, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 3
2023-05-22 12:40:42.523 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/__init__.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 2
2023-05-22 12:40:42.532 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/translations/cs.json, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 2
2023-05-22 12:40:42.537 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/const.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 2
2023-05-22 12:40:42.543 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/config_flow.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 2
2023-05-22 12:41:44.521 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/const.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 1
2023-05-22 12:41:44.529 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/translations/cs.json, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 1
2023-05-22 12:41:44.535 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/__init__.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 1
2023-05-22 12:41:44.540 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/config_flow.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 1
2023-05-22 12:42:46.522 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/const.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0
2023-05-22 12:42:46.530 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/__init__.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0
2023-05-22 12:42:46.536 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/translations/cs.json, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0
2023-05-22 12:42:46.542 WARNING (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/config_flow.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0
2023-05-22 12:42:48.549 ERROR (MainThread) [custom_components.hacs] <Integration basnijholt/adaptive-lighting> [const.py] was not downloaded.
2023-05-22 12:42:48.560 ERROR (MainThread) [custom_components.hacs] <Integration basnijholt/adaptive-lighting> [__init__.py] was not downloaded.
2023-05-22 12:42:48.566 ERROR (MainThread) [custom_components.hacs] <Integration basnijholt/adaptive-lighting> [cs.json] was not downloaded.
2023-05-22 12:42:48.570 ERROR (MainThread) [custom_components.hacs] <Integration basnijholt/adaptive-lighting> [config_flow.py] was not downloaded.
2023-05-22 12:42:48.575 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547000781552] Error handling message: Unknown error (unknown_error) Daniel Büttner from 127.0.0.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 216, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
    await self.async_install_repository()
  File "/config/custom_components/hacs/repositories/base.py", line 995, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details
```

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

Confid disabled for now

4.  Describe the bug and how to reproduce it:

I received a notification for a new update and clicked download. The download did not complete and left a broken integration.
I de-installed Adaptie Lighting and am trying to re-install it via HACS, but am getting the above error. 

I tried to manually clear the custom-components/adaptive-lighting dir, but that also didn't help. 

5. Steps to reproduce the behavior:

Go to HACS > Integrations. Search for Adaptive Lighting. Click Download. Wait.

**Comment by th3w1zard1** [comment]
Have you tried running `chmod 755 -Rv <folder>` and `chown` on the `custom_components` folder to ensure you have proper permissions?

Otherwise have you tried completing a full power cycle on your home assistant server?

Afterwards I'd check if you are able to download other HACS packages correctly. HACS servers might just have been restarting.

**Comment by basslet** [comment]
Other HACS are fine. I tried the download yesterday and today. Also tried the full power cycle on the RaPi.

**Comment by basnijholt** [comment]
I tagged 1.12.0 2 days ago but forgot to update the `manifest.json`. v1.12.0 includes all the fixes you made @th3w1zard1 :)

**Comment by basslet** [comment]
The download/update via HACS is still broken for me. I now cloned the files from your repo directly into custom_components, which works.

**Comment by basnijholt** [comment]
Since you seem to be the only one reporting this issue I think it must be something with your setup and likely a bug in HACS.

The link https://raw.githubusercontent.com/basnijholt/adaptive-lighting/1.12.0/custom_components/adaptive_lighting/config_flow.py works BTW.

Anyway, not a AL bug. Thanks for reporting though!
