### ISSUE TITLE
Strange errors from HASS when running automactions/scripts, even with no adaptive lighting lights.

### ISSUE THREAD

**Issue by cooljimy84** [basnijholt/adaptive-lighting#665]
# Home Assistant Adaptive Lighting Issue Template

## Bug Reports

If you need help with using or configuring Adaptive Lighting, please [open a Q&A discussion thread here](https://github.com/basnijholt/adaptive-lighting/discussions/new?category=q-a) instead.

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [X] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [X] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [X] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [X] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

```
2023-07-26 09:21:53.110 ERROR (MainThread) [homeassistant.components.automation.ep1_1_control] While executing automation automation.ep1_1_control
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/automation/__init__.py", line 659, in async_trigger
    await self.action_script.async_run(
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/script.py", line 1569, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/hass_utils.py", line 46, in service_func_proxy
    await intercept_func(call, data)
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/switch.py", line 1939, in _service_interceptor_turn_on_handler
    adaptive_switch = _switch_with_lights(self.hass, [entity_id])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/switch.py", line 307, in _switch_with_lights
    switches = _switches_with_lights(hass, lights)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/switch.py", line 291, in _switches_with_lights
    switch._expand_light_groups()
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/switch.py", line 977, in _expand_light_groups
    all_lights = _expand_light_groups(self.hass, self.lights)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/switch.py", line 624, in _expand_light_groups
    manager = hass.data[DOMAIN][ATTR_ADAPTIVE_LIGHTING_MANAGER]
              ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'


```

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

```
adaptive_lighting:
- name: "Frontdoor AL"
  lights: [light.esp6_led_ring]
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.5
  interval: 300
  min_brightness: 60
  max_brightness: 100
  min_color_temp: 3300
  max_color_temp: 6000
  sleep_brightness: 10
  sleep_color_temp: 2500
  sunrise_time: "06:45:00" # override the sunrise time
  sunrise_offset: "00:00:00"
  sunset_time: "19:30:00"
  sunset_offset: "00:00:00" # in seconds or '00:15:00'
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false
- name: "Our Bedroom AL"
  lights: [light.led_wheel]
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.5
  interval: 300
  min_brightness: 40
  max_brightness: 100
  min_color_temp: 3300
  max_color_temp: 5500
  sleep_brightness: 10
  sleep_color_temp: 2500
  sunrise_time: "06:45:00" # override the sunrise time
  sunrise_offset: "00:00:00"
  sunset_time: "19:30:00"
  sunset_offset: "00:00:00" # in seconds or '00:15:00'
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false
- name: "Up Lighter AL"
  lights: [light.led_uplighter]
  prefer_rgb_color: false
  transition: 30
  initial_transition: 1
  interval: 300
  min_brightness: 75
  max_brightness: 100
  min_color_temp: 2500
  max_color_temp: 5000
  sleep_brightness: 10
  sleep_color_temp: 2500
  sunrise_time: "06:45:00" # override the sunrise time
  sunrise_offset: "00:00:00"
  sunset_time: "19:30:00"
  sunset_offset: "00:00:00" # in seconds or '00:15:00'
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false
- name: "Kitchen RGB AL"
  lights: [light.kitchen_led]
  prefer_rgb_color: true
  transition: 30
  initial_transition: 1
  interval: 300
  min_brightness: 25
  max_brightness: 100
  min_color_temp: 2500
  max_color_temp: 4750
  sleep_brightness: 10
  sleep_color_temp: 2500
  sunrise_time: "06:45:00" # override the sunrise time
  sunrise_offset: "00:00:00"
  sunset_time: "19:30:00"
  sunset_offset: "00:00:00" # in seconds or '00:15:00'
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false
- name: "WinDoor RGB AL"
  lights: [light.wled_window,light.wled_door]
  prefer_rgb_color: false
  transition: 30
  initial_transition: 1
  interval: 300
  min_brightness: 25
  max_brightness: 100
  min_color_temp: 2500
  max_color_temp: 4750
  sleep_brightness: 10
  sleep_color_temp: 2500
  sunrise_time: "06:45:00" # override the sunrise time
  sunrise_offset: "00:00:00"
  sunset_time: "19:30:00"
  sunset_offset: "00:00:00" # in seconds or '00:15:00'
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false
- name: "TV WLED AL"
  lights: [light.wled_tv]
  prefer_rgb_color: true
  transition: 30
  initial_transition: 1
  interval: 300
  min_brightness: 20
  max_brightness: 25
  min_color_temp: 2500
  max_color_temp: 4750
  sleep_brightness: 10
  sleep_color_temp: 2500
  sunrise_time: "06:45:00" # override the sunrise time
  sunrise_offset: "00:00:00"
  sunset_time: "19:30:00"
  sunset_offset: "00:00:00" # in seconds or '00:15:00'
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false


```

3.  (If using Zigbee2MQTT), provide your configuration files (**remove all personal information before posting**):
    - `devices.yaml`
    - `groups.yaml`
    - `configuration.yaml` ⚠️; **Warning** _**REMOVE ALL of the PERSONAL INFORMATION BELOW before posting**_ ⚠️;
      - mqtt: `server`:
      - mqtt: `user`:
      - mqtt: `password`:
      - advanced: `pan_id`:
      - advanced: `network_key`:
      - anything in `log_syslog` if you use this
    - Brand and model number of problematic light(s)
```

```

4.  Describe the bug and how to reproduce it:
Run any automation or script that changes state of a light, weather the light is in the adaptive lighting config or not.

5. Steps to reproduce the behavior:
Run any automation or script that changes state of a light, weather the light is in the adaptive lighting config or not.

**Comment by cooljimy84** [comment]
This is the EP1-1 automation
```
- alias: EP1-1 Control
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: binary_sensor.ep1_1_occupancy
  action:
    - service_template: >-
        {% if trigger.to_state.state == 'on' %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      entity_id: light.ep1_1_status_led
```

**Comment by cooljimy84** [comment]
This seems to be httpcore==0.17.1 kinda issue as i'm running unsupported ubuntu pip install.
