### ISSUE TITLE
Home Assistant Core 2023.7.3, AL 1.15.0 works fine, 1.15.1> gives websocket_api errors even lastest 1.17.2

### ISSUE THREAD

**Issue by cooljimy84** [basnijholt/adaptive-lighting#666]
# Home Assistant Adaptive Lighting Issue Template

## Bug Reports

If you need help with using or configuring Adaptive Lighting, please [open a Q&A discussion thread here](https://github.com/basnijholt/adaptive-lighting/discussions/new?category=q-a) instead.

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [X] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [X] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [X] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [X] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

```
2023-07-26 16:00:23.980 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139786566094864] 'NoneType' object has no attribute 'data'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/hass_utils.py", line 46, in service_func_proxy
    await intercept_func(call, data)
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/switch.py", line 1843, in _service_interceptor_turn_on_handler
    adaptive_switch = find_switch_for_lights(self.hass, [entity_id])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/switch.py", line 313, in find_switch_for_lights
    switches = _get_switches_with_lights(hass, lights)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/switch.py", line 301, in _get_switches_with_lights
    switch._expand_light_groups()
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/switch.py", line 979, in _expand_light_groups
    all_lights = _expand_light_groups(self.hass, self.lights)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/adaptive_lighting/switch.py", line 608, in _expand_light_groups
    turn_on_off_listener = hass.data[DOMAIN][ATTR_TURN_ON_OFF_LISTENER]
                           ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2023-07-26 16:00:23.982 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected an 'light.turn_on('['light.led_uplighter']')' event with context.id='01H69BE9SBJHCJGBP8H2C7QN7G'

```

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

```
adaptive_lighting:
- name: "Frontdoor AL"
  lights: [light.esp6_led_ring]
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.5
  interval: 300
  min_brightness: 60
  max_brightness: 100
  min_color_temp: 3300
  max_color_temp: 6000
  sleep_brightness: 10
  sleep_color_temp: 2500
  sunrise_time: "06:45:00" # override the sunrise time
  sunrise_offset: "00:00:00"
  sunset_time: "19:30:00"
  sunset_offset: "00:00:00" # in seconds or '00:15:00'
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false
- name: "Our Bedroom AL"
  lights: [light.led_wheel]
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.5
  interval: 300
  min_brightness: 40
  max_brightness: 100
  min_color_temp: 3300
  max_color_temp: 5500
  sleep_brightness: 10
  sleep_color_temp: 2500
  sunrise_time: "06:45:00" # override the sunrise time
  sunrise_offset: "00:00:00"
  sunset_time: "19:30:00"
  sunset_offset: "00:00:00" # in seconds or '00:15:00'
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false
- name: "Up Lighter AL"
  lights: [light.led_uplighter]
  prefer_rgb_color: false
  transition: 30
  initial_transition: 1
  interval: 300
  min_brightness: 75
  max_brightness: 100
  min_color_temp: 2500
  max_color_temp: 5000
  sleep_brightness: 10
  sleep_color_temp: 2500
  sunrise_time: "06:45:00" # override the sunrise time
  sunrise_offset: "00:00:00"
  sunset_time: "19:30:00"
  sunset_offset: "00:00:00" # in seconds or '00:15:00'
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false
- name: "Kitchen RGB AL"
  lights: [light.kitchen_led]
  prefer_rgb_color: true
  transition: 30
  initial_transition: 1
  interval: 300
  min_brightness: 25
  max_brightness: 100
  min_color_temp: 2500
  max_color_temp: 4750
  sleep_brightness: 10
  sleep_color_temp: 2500
  sunrise_time: "06:45:00" # override the sunrise time
  sunrise_offset: "00:00:00"
  sunset_time: "19:30:00"
  sunset_offset: "00:00:00" # in seconds or '00:15:00'
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false
- name: "WinDoor RGB AL"
  lights: [light.wled_window,light.wled_door]
  prefer_rgb_color: false
  transition: 30
  initial_transition: 1
  interval: 300
  min_brightness: 25
  max_brightness: 100
  min_color_temp: 2500
  max_color_temp: 4750
  sleep_brightness: 10
  sleep_color_temp: 2500
  sunrise_time: "06:45:00" # override the sunrise time
  sunrise_offset: "00:00:00"
  sunset_time: "19:30:00"
  sunset_offset: "00:00:00" # in seconds or '00:15:00'
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false
- name: "TV WLED AL"
  lights: [light.wled_tv]
  prefer_rgb_color: true
  transition: 30
  initial_transition: 1
  interval: 300
  min_brightness: 20
  max_brightness: 25
  min_color_temp: 2500
  max_color_temp: 4750
  sleep_brightness: 10
  sleep_color_temp: 2500
  sunrise_time: "06:45:00" # override the sunrise time
  sunrise_offset: "00:00:00"
  sunset_time: "19:30:00"
  sunset_offset: "00:00:00" # in seconds or '00:15:00'
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false
```

3.  (If using Zigbee2MQTT), provide your configuration files (**remove all personal information before posting**):
    - `devices.yaml`
    - `groups.yaml`
    - `configuration.yaml` ⚠️; **Warning** _**REMOVE ALL of the PERSONAL INFORMATION BELOW before posting**_ ⚠️;
      - mqtt: `server`:
      - mqtt: `user`:
      - mqtt: `password`:
      - advanced: `pan_id`:
      - advanced: `network_key`:
      - anything in `log_syslog` if you use this
    - Brand and model number of problematic light(s)
```

```

4.  Describe the bug and how to reproduce it:
When running and script/automaction or clicking on the light in the web interface i get the above error.

5. Steps to reproduce the behavior:
upgrade from 1.15.0 (or below) to 1.15.1 (or any thing above) reboot run script or click light

**Comment by cooljimy84** [comment]
I did log this ticket this morning, but closed it as it thought it was due to my update to 2023.7.X but after rolling back and testing after each change i have pinned it down to the 1.15.0>1.15.1 update of AL
I am running in a Ubuntu machine with pip (so pretty unsupported) but this might help.

```
homeassistant@hass4:~/.homeassistant$ pip list
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Package                Version             
---------------------- --------------------
aiohttp                3.8.1               
aiosignal              1.2.0               
anyio                  3.6.1               
asn1crypto             0.24.0              
astral                 2.2                 
async-timeout          4.0.0               
atomicwrites           1.4.0               
attrs                  21.2.0              
Automat                0.8.0               
awesomeversion         21.11.0             
backports.zoneinfo     0.2.1               
bcrypt                 3.1.7               
blinker                1.4                 
bottle                 0.12.15             
certifi                2021.10.8           
cffi                   1.15.0              
chardet                3.0.4               
charset-normalizer     2.0.12              
ciso8601               2.2.0               
Click                  7.0                 
cloud-init             23.2.1              
colorama               0.4.3               
command-not-found      0.3                 
configobj              5.0.6               
constantly             15.1.0              
cryptography           35.0.0              
cycler                 0.10.0              
dbus-python            1.2.16              
distro                 1.4.0               
distro-info            0.23ubuntu1         
dnspython              1.16.0              
docker                 4.1.0               
entrypoints            0.3                 
fail2ban               0.11.1              
frozenlist             1.3.0               
future                 0.18.2              
Glances                3.1.3               
gpg                    1.13.1-unknown      
h11                    0.12.0              
homeassistant          2021.12.10          
httpcore               0.14.7              
httplib2               0.14.0              
httpx                  0.21.0              
hyperlink              19.0.0              
idna                   2.8                 
ifaddr                 0.1.7               
importlib-metadata     1.5.0               
incremental            16.10.1             
influxdb               5.2.0               
iotop                  0.6                 
Jinja2                 3.0.3               
jsonpatch              1.22                
jsonpointer            2.0                 
jsonschema             3.2.0               
keyring                18.0.1              
kiwisolver             1.0.1               
language-selector      0.1                 
launchpadlib           1.10.13             
lazr.restfulclient     0.14.2              
lazr.uri               1.0.3               
Markdown               3.1.1               
MarkupSafe             2.1.1               
matplotlib             3.1.2               
more-itertools         4.2.0               
multidict              6.0.2               
netifaces              0.10.4              
numpy                  1.17.4              
oauthlib               3.1.0               
olefile                0.46                
packaging              20.3                
PAM                    0.4.2               
pexpect                4.6.0               
Pillow                 7.0.0               
pip                    20.0.2              
ply                    3.11                
psutil                 5.5.1               
pyasn1                 0.4.2               
pyasn1-modules         0.2.1               
pycparser              2.21                
pycrypto               2.6.1               
pycryptodomex          3.6.1               
Pygments               2.3.1               
PyGObject              3.36.0              
PyHamcrest             1.9.0               
pyinotify              0.9.6               
PyJWT                  2.1.0               
pyOpenSSL              19.0.0              
pyparsing              2.4.6               
pyrsistent             0.15.5              
pyserial               3.4                 
pysmi                  0.3.2               
pysnmp                 4.4.6               
pystache               0.5.4               
python-apt             2.0.1+ubuntu0.20.4.1
python-dateutil        2.7.3               
python-debian          0.1.36+ubuntu1.1    
python-slugify         4.0.1               
pytz                   2019.3              
PyYAML                 6.0                 
requests               2.26.0              
requests-unixsocket    0.2.0               
rfc3986                1.5.0               
SecretStorage          2.3.1               
service-identity       18.1.0              
setuptools             45.2.0              
simplejson             3.16.0              
six                    1.14.0              
sniffio                1.2.0               
sos                    4.4                 
ssh-import-id          5.10                
systemd-python         234                 
text-unidecode         1.3                 
Twisted                18.9.0              
typing-extensions      4.2.0               
ubuntu-advantage-tools 8001                
ufw                    0.36                
unattended-upgrades    0.1                 
urllib3                1.25.8              
voluptuous             0.12.2              
voluptuous-serialize   2.5.0               
wadllib                1.3.3               
websocket-client       0.53.0              
wheel                  0.34.2              
yarl                   1.6.3               
zipp                   1.0.0               
zope.interface         4.7.1
```

**Comment by basnijholt** [comment]
This same issue was reported in https://github.com/basnijholt/adaptive-lighting/issues/658 where @manuelh19 eventually realized this was the problem: https://github.com/basnijholt/adaptive-lighting/issues/658#issuecomment-1650666208.

However, I believe I also prevent the problem from occurring in PR https://github.com/basnijholt/adaptive-lighting/pull/659 which I just merged. I also released v1.17.3 with this fix. 

Please let me know whether this works for you! 😄

**Comment by cooljimy84** [comment]
1.17.3 works perfectly for me !

Thank you very much for the help and the awesome project !

**Comment by cooljimy84** [comment]
Getting spammed with this in the log files, tho everything seems to be working fine.
```
2023-07-27 08:46:03.306 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:03.306 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:03.306 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:03.306 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:03.306 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:03.307 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:03.307 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:03.307 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:03.307 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:42.892 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:42.892 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:42.893 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:42.893 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:42.893 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:42.893 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:42.893 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:42.893 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data'
2023-07-27 08:46:42.893 ERROR (MainThread) [custom_components.adaptive_lighting.hass_utils] Error in service_func_proxy: 'NoneType' object has no attribute 'data
```

**Comment by basnijholt** [comment]
My suspicion is that this is because of old instances in the configuration. This was the problem of the other person reporting this issue (see link above). 

To prevent this, I have worked on proper removal when deleting the Adaptive Lighting switches from YAML. I merged #669 but still need to create a release.

**Comment by basnijholt** [comment]
It would be great to hear if since 1.17.4 this issue does not occur anymore 😄

**Comment by cooljimy84** [comment]
> It would be great to hear if since 1.17.4 this issue does not occur anymore smile

Sorry didn't realise you had already pushed out .4 (and now i see .5) 
Just installed .5 and all seems fine now.

Your a machine when it comes to these releases !
