### ISSUE TITLE
Switch error

### ISSUE THREAD

**Issue by mo1seev** [basnijholt/adaptive-lighting#81]
Logger: homeassistant.components.switch
Source: custom_components/adaptive_lighting/switch.py:800 
Integration: Switch (documentation, issues) 
First occurred: 23:10:36 (8 occurrences) 
Last logged: 23:36:38

Error adding entities for domain switch with platform adaptive_lighting
Error while setting up adaptive_lighting platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/adaptive_lighting/switch.py", line 604, in async_added_to_hass
    await self.async_turn_on(adapt_lights=not self._only_once)
  File "/config/custom_components/adaptive_lighting/switch.py", line 693, in async_turn_on
    await self._update_attrs_and_maybe_adapt_lights(
  File "/config/custom_components/adaptive_lighting/switch.py", line 829, in _update_attrs_and_maybe_adapt_lights
    await self._adapt_lights(lights, transition, force, context)
  File "/config/custom_components/adaptive_lighting/switch.py", line 867, in _adapt_lights
    await self._adapt_light(light, transition, force=force, context=context)
  File "/config/custom_components/adaptive_lighting/switch.py", line 800, in _adapt_light
    await turn_on(service_datas[0])
IndexError: list index out of range

**Comment by fpatrick** [comment]
I have the same error

**Comment by bohtho** [comment]
Nothing in 8 months? Did you guys find out why you got the error? I get the same on latest HA and AL component.

**Comment by cfdresearch** [comment]
Logger: homeassistant.components.switch
Source: custom_components/adaptive_lighting/switch.py:853
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 22:44:44 (2 occurrences)
Last logged: 22:44:47

Error adding entities for domain switch with platform adaptive_lighting
Error while setting up adaptive_lighting platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 781, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/adaptive_lighting/switch.py", line 655, in async_added_to_hass
    await self.async_turn_on(adapt_lights=not self._only_once)
  File "/config/custom_components/adaptive_lighting/switch.py", line 746, in async_turn_on
    await self._update_attrs_and_maybe_adapt_lights(
  File "/config/custom_components/adaptive_lighting/switch.py", line 882, in _update_attrs_and_maybe_adapt_lights
    await self._adapt_lights(lights, transition, force, context)
  File "/config/custom_components/adaptive_lighting/switch.py", line 920, in _adapt_lights
    await self._adapt_light(light, transition, force=force, context=context)
  File "/config/custom_components/adaptive_lighting/switch.py", line 853, in _adapt_light
    await turn_on(service_datas[0])
IndexError: list index out of range

## System Health

version | core-2022.2.9
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.15.21-v7l+
arch | armv7l
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4670
Installed Version | 1.23.0
Stage | running
Available Repositories | 986
Downloaded Repositories | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 13, 2022, 03:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.12
disk_total | 117.1 GB
disk_used | 11.2 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), MariaDB (2.4.0), Mosquitto broker (6.0.1), Zigbee2mqtt (1.23.0-1), Home Assistant Google Drive Backup (0.105.2), Samba share (9.5.1), Check Home Assistant configuration (3.10.0), ESPHome (2022.2.3), RPC Shutdown (2.2), Git pull (7.13.1), ZeroTier One (0.12.2), Grafana (7.4.1), Node-RED (11.0.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 12
views | 10
mode | yaml

</details>

**Comment by scobby** [comment]
I have this error too, think its a problem when detecting manual light interactions

**Comment by basnijholt** [comment]
A long time later, I have fixed this issue in https://github.com/basnijholt/adaptive-lighting/pull/317.

Will merge that PR as soon as I fixed all of the tests.
