### ISSUE TITLE
The WebApp is not loading

### ISSUE THREAD

**Issue by joaldes** [basnijholt/adaptive-lighting#886]
### Required information for bug reports:

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):
NA

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):
NA

3.  (If using Zigbee2MQTT), provide your configuration files (**remove all personal information before posting**):
NA

4.  Describe the bug and how to reproduce it:
The webapp doesn't load.  

5. Steps to reproduce the behavior:
Load the webpage: https://basnijholt.github.io/adaptive-lighting/

**Comment by jacobwtyler** [comment]
same issue

**Comment by dcarosone** [comment]
```console
skull
Error starting app!

Traceback (most recent call last):
  File "<exec>", line 207, in _start_app
  File "<exec>", line 141, in _install_requirements_from_dir
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 573, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 340, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 448, in add_requirement_inner
    await self.add_wheel(wheel, req.extras)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 463, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 337, in add_requirement
    return await self.add_requirement_inner(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 418, in add_requirement_inner
    if self.check_version_satisfied(req):
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 364, in check_version_satisfied
    raise ValueError(
ValueError: Requested 'click>=8.1.7', but click==8.1.3 is already installed
```

**Comment by danbo-ark** [comment]
The same error is occurring for me

**Comment by basnijholt** [comment]
Sorry folks, just fixed it and pinned all dependencies to prevent it from breaking again!
