### ISSUE TITLE
some errors on a new install of this component 

### ISSUE THREAD

**Issue by ctrl50** [basnijholt/adaptive-lighting#9]
Just installed it as shown in your reddit video. Set the sunrise and sunset times, and added a couple lights.

Lights arent changing at all. and giving these erorrs. not really sure how to proceed since the times I set are correct.

edit: Also switch.adaptive_lighting_testing is Unavailable

```
Oct 13 15:44:50 server hass[5180]: 2020-10-13 15:44:50 ERROR (MainThread) [custom_components.adaptive_lighting.switch] testing: The sun events ('sunset', 'solar_noon', 'sunrise', 'solar_midnight') are not in the expected order. The Adaptive Lighting integration will not work! This might happen if your sunrise/sunset offset is too large or your manually set sunrise/sunset time is past/before noon/midnight.
Oct 13 15:44:50 server hass[5180]: 2020-10-13 15:44:50 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Oct 13 15:44:50 server hass[5180]: Traceback (most recent call last):
Oct 13 15:44:50 server hass[5180]:   File "/home/ctrl/.homeassistant/custom_components/adaptive_lighting/switch.py", line 739, in _light_event
Oct 13 15:44:50 server hass[5180]:     await self._update_attrs_and_maybe_adapt_lights(
Oct 13 15:44:50 server hass[5180]:   File "/home/ctrl/.homeassistant/custom_components/adaptive_lighting/switch.py", line 650, in _update_attrs_and_maybe_adapt_lights
Oct 13 15:44:50 server hass[5180]:     self._settings = self._sun_light_settings.get_settings(
Oct 13 15:44:50 server hass[5180]:   File "/home/ctrl/.homeassistant/custom_components/adaptive_lighting/switch.py", line 927, in get_settings
Oct 13 15:44:50 server hass[5180]:     percent = self.calc_percent()
Oct 13 15:44:50 server hass[5180]:   File "/home/ctrl/.homeassistant/custom_components/adaptive_lighting/switch.py", line 890, in calc_percent
Oct 13 15:44:50 server hass[5180]:     today = self.relevant_events(now)
Oct 13 15:44:50 server hass[5180]:   File "/home/ctrl/.homeassistant/custom_components/adaptive_lighting/switch.py", line 878, in relevant_events
Oct 13 15:44:50 server hass[5180]:     events = [
Oct 13 15:44:50 server hass[5180]:   File "/home/ctrl/.homeassistant/custom_components/adaptive_lighting/switch.py", line 879, in <listcomp>
Oct 13 15:44:50 server hass[5180]:     self.get_sun_events(now + timedelta(days=days)) for days in [-1, 0, 1]
Oct 13 15:44:50 server hass[5180]:   File "/home/ctrl/.homeassistant/custom_components/adaptive_lighting/switch.py", line 872, in get_sun_events
Oct 13 15:44:50 server hass[5180]:     raise ValueError(msg)
Oct 13 15:44:50 server hass[5180]: ValueError: testing: The sun events ('sunset', 'solar_noon', 'sunrise', 'solar_midnight') are not in the expected order. The Adaptive Lighting integration will not work! This might happen if your sunrise/sunset offset is too large or your manually set sunrise/sunset time is past/before noon/midnight.


```

**Comment by basnijholt** [comment]
Hmm, did you read the error message?
> ValueError: testing: The sun events ('sunset', 'solar_noon', 'sunrise', 'solar_midnight') are not in the expected order. The Adaptive Lighting integration will not work! This might happen if your sunrise/sunset offset is too large or your manually set sunrise/sunset time is past/before noon/midnight.

If you did not manually set the sunset and sunrise (with offsets), please tell me how you configured the integration.

**Comment by basnijholt** [comment]
This is the same issue as #7, let's continue there.
