### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by thargy** [basnijholt/adaptive-lighting#901]
# Home Assistant Adaptive Lighting Issue Template

## Bug Reports

If you need help with using or configuring Adaptive Lighting, please [open a Q&A discussion thread here](https://github.com/basnijholt/adaptive-lighting/discussions/new?category=q-a) instead.

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [x] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [x] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

This error occurred once in last 24 hours afterI was having memory issues (see #899).  Raising due to error message requesting.  Can confirm not Hue Bridge lights, and errors occurred after Bridge lights were removed.

```log
2024-01-08 00:30:29.094 WARNING (MainThread) [custom_components.adaptive_lighting.switch] Detected an 'off' → 'on' event for 'light.ensuite_spots' with context.id='01HKK7MQ4T:al:IVXH:lght:1H' and event='<Event state_changed[L]: entity_id=light.ensuite_spots, old_state=<state light.ensuite_spots=off; min_color_temp_kelvin=2202, max_color_temp_kelvin=6535, min_mireds=153, max_mireds=454, effect_list=['blink', 'breathe', 'okay', 'channel_change', 'candle', 'finish_effect', 'stop_effect', 'stop_hue_effect'], supported_color_modes=['color_temp'], color_mode=None, brightness=None, color_temp_kelvin=None, color_temp=None, hs_color=None, rgb_color=None, xy_color=None, effect=None, friendly_name=Ensuite Spots, supported_features=44 @ 2024-01-08T00:30:28.003201+00:00>, new_state=<state light.ensuite_spots=on; min_color_temp_kelvin=2202, max_color_temp_kelvin=6535, min_mireds=153, max_mireds=454, effect_list=['blink', 'breathe', 'okay', 'channel_change', 'candle', 'finish_effect', 'stop_effect', 'stop_hue_effect'], supported_color_modes=['color_temp'], color_mode=color_temp, brightness=1, color_temp_kelvin=5000, color_temp=200, hs_color=(27.001, 19.243), rgb_color=(255, 228, 205), xy_color=(0.372, 0.35), effect=None, friendly_name=Ensuite Spots, supported_features=44 @ 2024-01-08T00:30:29.093752+00:00>>', triggered by the adaptive_lighting integration itself, which *should* not happen. If you see this please submit an issue with your full logs at https://github.com/basnijholt/adaptive-lighting
2024-01-08 00:30:29.096 WARNING (MainThread) [custom_components.adaptive_lighting.switch] Detected an 'off' → 'on' event for 'light.ensuite_spots' with context.id='01HKK7MQ4T:al:IVXH:lght:1H' and event='<Event state_changed[L]: entity_id=light.ensuite_spots, old_state=<state light.ensuite_spots=off; min_color_temp_kelvin=2202, max_color_temp_kelvin=6535, min_mireds=153, max_mireds=454, effect_list=['blink', 'breathe', 'okay', 'channel_change', 'candle', 'finish_effect', 'stop_effect', 'stop_hue_effect'], supported_color_modes=['color_temp'], color_mode=None, brightness=None, color_temp_kelvin=None, color_temp=None, hs_color=None, rgb_color=None, xy_color=None, effect=None, friendly_name=Ensuite Spots, supported_features=44 @ 2024-01-08T00:30:28.003201+00:00>, new_state=<state light.ensuite_spots=on; min_color_temp_kelvin=2202, max_color_temp_kelvin=6535, min_mireds=153, max_mireds=454, effect_list=['blink', 'breathe', 'okay', 'channel_change', 'candle', 'finish_effect', 'stop_effect', 'stop_hue_effect'], supported_color_modes=['color_temp'], color_mode=color_temp, brightness=1, color_temp_kelvin=5000, color_temp=200, hs_color=(27.001, 19.243), rgb_color=(255, 228, 205), xy_color=(0.372, 0.35), effect=None, friendly_name=Ensuite Spots, supported_features=44 @ 2024-01-08T00:30:29.093752+00:00>>', triggered by the adaptive_lighting integration itself, which *should* not happen. If you see this please submit an issue with your full logs at https://github.com/basnijholt/adaptive-lighting
```

The following log (possibly unrelated?) has been occurring frequently all day:

```log
2024-01-08 18:13:21.926 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/adaptive_lighting/switch.py", line 2272, in turn_on_off_event_listener
    on(eid, event)
  File "/config/custom_components/adaptive_lighting/switch.py", line 2249, in on
    and event.time_fired > timer.start_time  # type: ignore[operator]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'datetime.datetime' and 'NoneType'
```

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

See (#899)

3.  (If using Zigbee2MQTT), provide your configuration files (**remove all personal information before posting**):

See (#899)

4.  Describe the bug and how to reproduce it:

Not sure what impact is being had.

5. Steps to reproduce the behavior:

New install.

**Comment by tivoo** [comment]
Experiencing the same TypeError. Would be great if this can be resolved @basnijholt

**Comment by basnijholt** [comment]
The `timer.start_time` TypeError was fixed in #1295. I preserved the separate self-triggered off/on warning in #860, which remains open. Closing this combined report.
